const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright')
const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')
const base = 'http://127.0.0.1:5173'
async function json(r) { assert(r.ok(), await r.text()); return r.json() }
async function nav(page, name) { await page.locator('.side-nav').getByText(name, { exact: true }).click() }
async function profile(page) { await page.getByRole('button', { name: '个人主页', exact: true }).filter({ visible: true }).click(); await page.locator('.profile-page').waitFor() }
async function main() {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const contexts = [await browser.newContext({ viewport: { width: 1440, height: 960 } }), await browser.newContext({ viewport: { width: 1440, height: 960 } })]
  const admin = await browser.newContext()
  const users = [], failures = [], pages = []
  let circle
  try {
    for (let i = 0; i < contexts.length; i++) users.push(await json(await contexts[i].request.post(base + '/api/auth/register', { data: { username: `socialui_${Date.now()}_${i}`, password: 'testpass1234', nickname: ['旅友甲', '旅友乙'][i] } })))
    circle = await json(await contexts[0].request.post(base + '/api/circles', { data: { name: '好友旅行影集', description: '一起留下回忆' } }))
    const post = await json(await contexts[0].request.post(`${base}/api/circles/${circle.id}/posts`, { multipart: { event_date: '2026-10-01', content: '一起走过的旅途', files: { name: 'friends.jpg', mimeType: 'image/jpeg', buffer: fs.readFileSync(path.resolve(__dirname, '../frontend/user/public/preview-assets/friends.jpg')) } } }))
    for (const context of contexts) { const page = await context.newPage(); pages.push(page); page.on('pageerror', e => failures.push(e.message)); page.on('console', m => { if (m.type() === 'warning' && m.text().includes('[Vue warn]')) failures.push(m.text()) }); await page.goto(base) }
    const [owner, member] = pages
    await nav(member, '圈子')
    await member.getByPlaceholder('例如 DEMO2026', { exact: true }).fill(circle.invite_code)
    await member.getByRole('button', { name: '加入圈子', exact: true }).click()
    await member.locator('.status-label').filter({ hasText: '等待审核' }).waitFor()
    assert((await json(await contexts[1].request.get(base + '/api/circles'))).length === 0)
    await owner.reload()
    await nav(owner, '圈子')
    await owner.locator('.circle-management .social-row').filter({ hasText: '旅友乙' }).getByRole('button', { name: '通过', exact: true }).click()
    await owner.locator('.member-management-row').filter({ hasText: '旅友乙' }).waitFor()
    await owner.getByRole('button', { name: '设为管理员：旅友乙', exact: true }).click()
    await owner.locator('.confirm-card').getByRole('button', { name: '确定', exact: true }).click()
    await owner.getByRole('button', { name: '撤销管理员：旅友乙', exact: true }).waitFor()
    await owner.getByRole('button', { name: '发布公告', exact: true }).click()
    await owner.locator('.social-form').getByLabel('公告标题', { exact: true }).fill('周末一起出发')
    await owner.locator('.social-form').getByLabel('公告内容', { exact: true }).fill('周六下午见，一起记录新的回忆。')
    await owner.locator('.modal-card').getByRole('button', { name: '发布公告', exact: true }).click()
    await owner.locator('.announcement-row').filter({ hasText: '周末一起出发' }).waitFor()
    for (const width of [1440, 768, 390]) { await owner.setViewportSize({ width, height: width === 390 ? 844 : 960 }); await owner.locator('.body-grid').evaluate(el => el.scrollTop = 0); await owner.waitForTimeout(250); assert(await owner.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `circle overflow ${width}`); await owner.screenshot({ path: path.resolve(__dirname, `../.shots/2026-10-01-social-circle-${width}.png`) }) }
    await owner.setViewportSize({ width: 1440, height: 960 })
    await member.reload()
    await member.locator('.featured-story .story-image').waitFor()
    await member.locator('.featured-story .story-image').click()
    await member.locator('.record-original.ready').waitFor()
    await member.getByRole('button', { name: '点赞', exact: true }).click()
    await member.getByRole('button', { name: '取消点赞', exact: true }).waitFor()
    await member.getByRole('button', { name: '收藏记录', exact: true }).click()
    await member.getByRole('button', { name: '新建收藏夹', exact: true }).click()
    await member.getByLabel('收藏夹名称', { exact: true }).fill('旅途中的人')
    await member.getByLabel('向指定朋友圈分享', { exact: true }).check()
    await member.locator('.folder-share-options').getByLabel('好友旅行影集', { exact: true }).check()
    await member.getByRole('button', { name: '保存收藏夹', exact: true }).click()
    await member.getByRole('button', { name: '保存收藏', exact: true }).click()
    await member.locator('.folder-pick-row').waitFor({ state: 'hidden' })
    await member.locator('input[aria-label="评论内容"]').fill('一起留下更多回忆')
    await member.getByRole('button', { name: '发送评论', exact: true }).click()
    await member.locator('.detail-comment').filter({ hasText: '一起留下更多回忆' }).waitFor()
    await member.keyboard.press('Escape')
    await member.locator('.record-backdrop').waitFor({ state: 'hidden' })
    await profile(member)
    await member.getByRole('button', { name: '账号设置', exact: true }).click()
    await member.getByRole('button', { name: '修改头像', exact: true }).click()
    await member.locator('.avatar-edit-button + input[type=file]').setInputFiles(path.resolve(__dirname, '../frontend/user/public/preview-assets/friends.jpg'))
    await member.locator('.avatar-crop-viewport img').waitFor()
    await member.getByLabel('头像缩放', { exact: true }).fill('1.4')
    await member.getByRole('button', { name: '使用此头像', exact: true }).click()
    await member.getByLabel('昵称', { exact: true }).fill('拾光同行')
    await member.locator('.modal-card').getByRole('button', { name: '保存修改', exact: true }).click()
    await member.locator('.profile-identity h2').filter({ hasText: '拾光同行' }).waitFor()
    await member.waitForFunction(() => { const img = document.querySelector('.profile-avatar img'); return img?.complete && img.naturalWidth === 256 })
    await member.locator('.profile-tabs').getByRole('button', { name: '收藏', exact: true }).click()
    await member.locator('.favorite-record').waitFor()
    await member.locator('.favorite-record').click()
    await member.locator('.record-original.ready').waitFor()
    await member.keyboard.press('Escape')
    await member.locator('.record-backdrop').waitFor({ state: 'hidden' })
    for (const width of [1440, 768, 390]) { await member.setViewportSize({ width, height: width === 390 ? 844 : 960 }); await member.locator('.body-grid').evaluate(el => el.scrollTop = 0); await member.waitForTimeout(250); assert(await member.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `favorites overflow ${width}`); await member.screenshot({ path: path.resolve(__dirname, `../.shots/2026-10-01-social-favorites-${width}.png`) }) }
    await member.locator('.profile-tabs').getByRole('button', { name: '消息', exact: true }).click()
    await member.locator('.message-row').first().waitFor()
    const messageCount = await member.locator('.message-row').count()
    await member.route('**/api/me/notifications/*/read', route => route.abort('failed'))
    await member.getByRole('button', { name: '标为已读', exact: true }).first().click()
    await member.locator('.message-center [role=alert]').waitFor()
    assert.equal(await member.locator('.message-row').count(), messageCount, 'failed message operation preserves context')
    await member.unroute('**/api/me/notifications/*/read')
    await member.getByRole('button', { name: '刷新消息', exact: true }).click()
    await member.locator('.message-center [role=alert]').waitFor({ state: 'hidden' })
    await member.screenshot({ path: path.resolve(__dirname, '../.shots/2026-10-01-social-messages-390.png') })
    await member.getByRole('button', { name: '全部已读', exact: true }).click()
    assert((await json(await contexts[1].request.get(base + '/api/me/notifications'))).unread_count === 0)
    await member.getByRole('button', { name: '账号设置', exact: true }).click()
    await member.getByRole('button', { name: '修改密码', exact: true }).click()
    await member.getByLabel('当前密码', { exact: true }).fill('wrongpass1234')
    await member.getByLabel('新密码', { exact: true }).fill('updatedpass1234')
    await member.getByLabel('确认新密码', { exact: true }).fill('differentpass1234')
    await member.getByRole('button', { name: '保存修改', exact: true }).click()
    await member.getByRole('alert').filter({ hasText: '两次新密码不一致' }).waitFor()
    await member.getByLabel('确认新密码', { exact: true }).fill('updatedpass1234')
    await member.getByRole('button', { name: '保存修改', exact: true }).click()
    await member.getByRole('alert').filter({ hasText: '当前密码错误' }).waitFor()
    assert.equal(await member.getByLabel('新密码', { exact: true }).inputValue(), 'updatedpass1234')
    await member.getByLabel('当前密码', { exact: true }).fill('testpass1234')
    await member.getByRole('button', { name: '保存修改', exact: true }).click()
    await member.getByLabel('当前密码', { exact: true }).waitFor({ state: 'hidden' })
    assert((await contexts[1].request.get(base + '/api/auth/me')).ok(), 'password change retains this session')
    await profile(owner)
    await owner.locator('.profile-tabs').getByRole('button', { name: '收藏', exact: true }).click()
    await owner.getByRole('button', { name: '圈内分享', exact: true }).click()
    await owner.locator('.favorite-record').waitFor()
    assert((await owner.getByRole('button', { name: '编辑收藏夹', exact: true }).count()) === 0)
    await owner.locator('.favorite-record').click()
    await owner.locator('.record-original.ready').waitFor()
    await owner.locator('.detail-comment').filter({ hasText: '一起留下更多回忆' }).getByRole('button', { name: '回复', exact: true }).click()
    await owner.getByLabel('评论内容', { exact: true }).fill('下次再出发')
    await owner.getByRole('button', { name: '发送评论', exact: true }).click()
    await owner.locator('.detail-comment').filter({ hasText: '回复' }).filter({ hasText: '下次再出发' }).waitFor()
    await owner.keyboard.press('Escape')
    await owner.locator('.record-backdrop').waitFor({ state: 'hidden' })
    assert((await json(await contexts[0].request.get(`${base}/api/posts/${post.id}`))).like_count === 1)
    assert.deepEqual(failures, [])
    console.log('Social browser checks passed: join approval, role appointment, announcement, avatar crop, nickname, likes, replies, shared collections, messages, desktop/tablet/mobile and nested dialogs.')
  } catch (e) { for (let i = 0; i < pages.length; i++) await pages[i].screenshot({ path: path.resolve(__dirname, `../.shots/social-failure-${i}.png`) }); throw e }
  finally {
    if (circle) await contexts[0].request.delete(`${base}/api/circles/${circle.id}`)
    await json(await admin.request.post(base + '/api/admin/auth/login', { data: { username: 'admin', password: 'admin123' } }))
    for (const u of users) await json(await admin.request.delete(`${base}/api/admin/users/${u.id}`, { data: { reason: '社交界面验证账号清理' } }))
    await browser.close()
  }
}
main().catch(e => { console.error(e); process.exitCode = 1 })
