const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const shots = path.resolve(__dirname, '../.shots')
fs.mkdirSync(shots, { recursive: true })

async function main() {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const failures = []
  const context = await browser.newContext({ viewport: { width:1440, height:960 } })
  const page = await context.newPage()
  page.on('pageerror', e => failures.push(e.message))
  page.on('console', m => { if(m.type()==='warning' && m.text().includes('[Vue warn]')) failures.push(m.text()) })
  await page.goto('http://127.0.0.1:5173')
  await page.locator('#login-name').fill('demo_a')
  await page.locator('#login-password').fill('demo1234')
  await page.locator('.login-form button[type=submit]').click()
  await page.locator('.featured-story img').waitFor()
  await page.waitForTimeout(600)
  await page.screenshot({path:path.join(shots,'2026-10-01-feed-desktop.png')})
  await page.locator('.featured-story .story-image').click()
  await page.locator('.record-original.ready').waitFor()
  await page.waitForTimeout(320)
  await page.screenshot({path:path.join(shots,'2026-10-01-detail-desktop.png')})
  await page.keyboard.press('Escape')
  await page.locator('.record-backdrop').waitFor({state:'hidden'})
  assert(await page.locator('.featured-story .story-image').evaluate(el=>el===document.activeElement))
  await page.locator('.side-nav').getByText('生活痕迹线').click()
  await page.locator('.chronicle-story.is-visible').first().waitFor()
  await page.waitForTimeout(400)
  await page.screenshot({path:path.join(shots,'2026-10-01-timeline-desktop.png')})
  await page.locator('.chronicle-images button').first().click()
  await page.locator('.record-original.ready').waitFor()
  await page.keyboard.press('Escape')
  await page.locator('.record-backdrop').waitFor({state:'hidden'})
  await page.getByRole('button',{name:'足迹地图',exact:true}).click()
  await page.locator('.leaflet-overlay-pane path').first().waitFor()
  assert(await page.locator('.leaflet-overlay-pane path').count()>20)
  await page.screenshot({path:path.join(shots,'2026-10-01-map-desktop.png')})
  await page.locator('.side-nav').getByText('共同相册').click()
  await page.locator('.album-grid button').first().waitFor()
  await page.locator('.album-grid button').first().click()
  await page.locator('.record-dialog').waitFor()
  await page.keyboard.press('Escape')
  await page.locator('.record-backdrop').waitFor({state:'hidden'})
  await page.locator('.compose-side').click()
  await page.locator('#memory-text').fill('未发布的测试草稿')
  await page.locator('.side-nav').getByText('照片墙').click()
  await page.locator('.confirm-card').waitFor()
  await page.locator('.confirm-card').getByRole('button',{name:'取消',exact:true}).click()
  assert(await page.locator('#memory-text').inputValue()==='未发布的测试草稿')
  await page.locator('.side-nav').getByText('照片墙').click()
  await page.locator('.confirm-card').getByRole('button',{name:'丢弃草稿',exact:true}).click()
  await page.locator('.featured-story').waitFor()
  for (const width of [768,390]) {
    await page.setViewportSize({width,height:844})
    const nav=page.locator(width===390?'.mobile-nav':'.side-nav')
    await nav.getByText('照片墙',{exact:true}).click()
    await page.locator('.featured-story').waitFor()
    await page.waitForTimeout(300)
    await page.locator('.body-grid').evaluate(el=>el.scrollTop=0)
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`)
    await page.screenshot({path:path.join(shots,`2026-10-01-feed-${width}.png`)})
    await nav.getByText(width===390?'时间轴':'生活痕迹线',{exact:true}).click()
    await page.locator('.chronicle').waitFor()
    await page.getByRole('button',{name:'影集时间线',exact:true}).click()
    await page.waitForTimeout(300)
    await page.locator('.body-grid').evaluate(el=>el.scrollTop=0)
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`timeline overflow ${width}`)
    await page.screenshot({path:path.join(shots,`2026-10-01-timeline-${width}.png`)})
  }
  await page.emulateMedia({reducedMotion:'reduce'})
  assert(await page.locator('.chronicle-story').first().evaluate(el=>getComputedStyle(el).opacity)==='1')
  await page.setViewportSize({width:1440,height:960})
  let releaseFeed
  const feedFailure = new Promise(resolve => { releaseFeed = resolve })
  await page.route('**/api/circles/*/posts',async route=>{await feedFailure;await route.abort('failed')})
  await page.reload({waitUntil:'domcontentloaded'})
  await page.locator('.feed-skeleton').waitFor()
  releaseFeed()
  await page.locator('.empty-state').getByRole('button',{name:'重试',exact:true}).waitFor()
  await page.unroute('**/api/circles/*/posts')
  await page.locator('.empty-state').getByRole('button',{name:'重试',exact:true}).click()
  await page.locator('.featured-story').waitFor()
  await context.close()
  const adminContext=await browser.newContext({viewport:{width:1440,height:960}})
  const admin=await adminContext.newPage()
  admin.on('pageerror',e=>failures.push(e.message))
  await admin.goto('http://127.0.0.1:5174')
  await admin.locator('#login-layer.open').waitFor()
  await admin.locator('#login-layer button[type=submit]').click()
  await admin.locator('#login-layer.open').waitFor({state:'hidden'})
  await admin.waitForTimeout(400)
  await admin.screenshot({path:path.join(shots,'2026-10-01-admin-desktop.png')})
  await admin.setViewportSize({width:390,height:844})
  assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'admin overflow')
  await admin.screenshot({path:path.join(shots,'2026-10-01-admin-mobile.png')})
  await browser.close()
  assert.deepEqual(failures,[])
  console.log('UI checks passed: desktop/tablet/mobile, detail, timeline, map, draft guard, reduced motion, admin.')
}
main().catch(e=>{console.error(e);process.exit(1)})
