const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright')
const assert=require('node:assert/strict')
const path=require('node:path')
const base='http://127.0.0.1:5173',adminBase='http://127.0.0.1:5174'
const shots=path.resolve(__dirname,'../.shots')
const fixture=path.resolve(__dirname,'../frontend/user/public/preview-assets')
async function json(response){assert(response.ok(),await response.text());return response.json()}
async function main(){
  const browser=await chromium.launch({channel:'msedge',headless:true})
  const context=await browser.newContext({viewport:{width:1440,height:960}})
  const adminContext=await browser.newContext({viewport:{width:1440,height:960}})
  const user=await json(await context.request.post(base+'/api/auth/register',{data:{username:'ui_'+Date.now(),password:'testpass1234',nickname:'旅行验证'}}))
  let circle, page, adminPage
  const failures=[]
  try{
    circle=await json(await context.request.post(base+'/api/circles',{data:{name:'独立旅行验证'}}))
    page=await context.newPage();page.on('pageerror',e=>failures.push(e.stack||e.message))
    await page.goto(base)
    await page.locator('.side-nav').getByText('生活痕迹线').click()
    await page.getByRole('button',{name:'新建时间线',exact:true}).click()
    await page.locator('.line-form').getByLabel('名称',{exact:true}).fill('云南旅程')
    await page.getByLabel('时间线类型',{exact:true}).selectOption('travel')
    await page.getByRole('button',{name:'保存时间线',exact:true}).click()
    await page.locator('.line-tree button.active').filter({hasText:'云南旅程'}).waitFor()
    await page.locator('.side-nav').getByText('共同相册').click()
    await page.getByRole('button',{name:'创建分册',exact:true}).click()
    await page.locator('#new-album-title').fill('云南影集')
    await page.locator('#new-album-line').selectOption({label:'云南旅程'})
    await page.locator('.modal-card').getByRole('button',{name:'创建',exact:true}).click()
    await page.locator('#album-title-top').filter({hasText:'云南影集'}).waitFor()
    await page.getByRole('button',{name:'加入接力',exact:true}).click()
    await page.locator('#memory-text').fill('大理的风与洱海')
    await page.locator('#memory-date').fill('2026-09-28')
    await page.locator('#photo-input').setInputFiles([path.join(fixture,'friends.jpg'),path.join(fixture,'flowers.jpg'),path.join(fixture,'city.jpg')])
    assert(await page.locator('.upload-item').count()===3)
    await page.getByRole('button',{name:'后移照片'}).first().click()
    assert((await page.locator('.upload-item > small').first().textContent())==='flowers.jpg')
    await page.getByRole('button',{name:'添加旅行地点',exact:true}).click()
    await page.getByRole('combobox',{name:'搜索城市或省份',exact:true}).fill('大理')
    await page.getByRole('option').filter({hasText:'大理白族自治州'}).click()
    assert(await page.locator('.leaflet-interactive').count()>0)
    await page.locator('button[type=submit]').filter({hasText:'发布记录'}).click()
    await page.locator('#album-title-top').waitFor()
    await page.locator('#album-detail-grid button').first().click()
    await page.locator('.record-original.ready').waitFor()
    assert(await page.locator('.gallery-thumbs button').count()===3)
    await page.keyboard.press('ArrowRight')
    assert((await page.locator('.gallery-counter').textContent()).includes('2 / 3'))
    await page.getByRole('button',{name:'编辑记录',exact:true}).click()
    await page.locator('.record-edit').getByLabel('记录内容',{exact:true}).fill('编辑后的旅行回忆')
    await page.locator('.record-edit').getByLabel('生活日期',{exact:true}).fill('2025-08-02')
    await page.getByRole('button',{name:'保存修改',exact:true}).click()
    await page.locator('.record-content').filter({hasText:'编辑后的旅行回忆'}).waitFor()
    await page.locator('input[aria-label="评论内容"]').fill('旅行评论验证')
    await page.getByRole('button',{name:'发送评论',exact:true}).click()
    await page.locator('.detail-comment').filter({hasText:'旅行评论验证'}).waitFor()
    await page.getByRole('button',{name:'举报',exact:true}).click()
    await page.locator('#report-type').selectOption('其他')
    await page.getByLabel('举报说明',{exact:true}).fill('独立测试举报')
    await page.getByRole('button',{name:'提交举报',exact:true}).click()
    await page.locator('.report-form').waitFor({state:'hidden'})
    await page.keyboard.press('Escape')
    await page.locator('.record-backdrop').waitFor({state:'hidden'})
    const albums=await json(await context.request.get(base+`/api/circles/${circle.id}/albums`))
    await json(await context.request.post(base+`/api/circles/${circle.id}/posts`,{multipart:{event_date:'2026-09-29',content:'上海的第二段足迹',album_id:String(albums[0].id),latitude:'31.2304',longitude:'121.4737',location_name:'上海',files:{name:'city.jpg',mimeType:'image/jpeg',buffer:require('node:fs').readFileSync(path.join(fixture,'city.jpg'))}}}))
    await page.locator('.side-nav').getByText('生活痕迹线').click()
    await page.locator('.chronicle-story').first().waitFor()
    await page.getByRole('button',{name:'足迹地图',exact:true}).click()
    await page.locator('.footprint-list button').first().waitFor()
    assert(await page.locator('.footprint-list button').count()===2)
    await page.waitForTimeout(350)
    await page.screenshot({path:path.join(shots,'2026-10-01-map-footprints.png')})
    await page.setViewportSize({width:390,height:844})
    await page.waitForTimeout(350)
    assert(await page.evaluate(()=>window.scrollY===0),'root scroll must remain locked')
    assert(await page.locator('.footprint-map').evaluate(el=>{const frame=el.getBoundingClientRect();return [...el.querySelectorAll('.leaflet-overlay-pane path')].every(path=>{const b=path.getBoundingClientRect();return b.left>=frame.left-2&&b.right<=frame.right+2&&b.top>=frame.top-2&&b.bottom<=frame.bottom+2})}),'all map boundaries and footprints must fit on mobile')
    await page.screenshot({path:path.join(shots,'2026-10-01-map-footprints-mobile.png')})
    await page.setViewportSize({width:1440,height:960})
    await json(await adminContext.request.post(adminBase+'/api/admin/auth/login',{data:{username:'admin',password:'admin123'}}))
    adminPage=await adminContext.newPage();adminPage.on('pageerror',e=>failures.push(e.message))
    await adminPage.goto(adminBase)
    await adminPage.locator('.nav').getByText('内容审核').click()
    await adminPage.locator('#review-rows tr').filter({hasText:'编辑后的旅行回忆'}).getByRole('button',{name:'查看',exact:true}).click()
    await adminPage.locator('.evidence-grid button').first().waitFor()
    assert(await adminPage.locator('.evidence-grid button').count()===3)
    await adminPage.locator('.evidence-grid button').last().click()
    await adminPage.locator('.evidence-viewer img').waitFor()
    await adminPage.keyboard.press('Escape')
    await adminPage.locator('.evidence-viewer').waitFor({state:'hidden'})
    await adminPage.getByRole('button',{name:'驳回举报',exact:true}).click()
    await adminPage.locator('#action-reason').selectOption({label:'重复举报'})
    await adminPage.locator('#modal-submit').click()
    await adminPage.locator('#modal-layer').waitFor({state:'hidden'})
    await adminPage.locator('#drawer-body .badge').filter({hasText:'已驳回'}).waitFor()
    await adminPage.screenshot({path:path.join(shots,'2026-10-01-admin-review.png')})
    // The video fixture is uploaded only to this disposable circle.
    const video=await json(await context.request.post(base+`/api/circles/${circle.id}/posts`,{multipart:{event_date:'2026-10-01',content:'真实视频播放验证',files:{name:'flower.mp4',mimeType:'video/mp4',buffer:require('node:fs').readFileSync(path.resolve(__dirname,'fixtures/flower.mp4'))}}}))
    await page.reload();await page.locator('.featured-story .story-image').waitFor()
    await page.locator('.featured-story .story-image').click()
    await page.locator('.record-stage video').waitFor()
    await page.waitForFunction(()=>document.querySelector('.record-stage video')?.readyState>=2)
    await page.locator('.record-stage video').evaluate(async el=>{await el.play();el.currentTime=Math.min(2,el.duration/2)})
    await page.waitForTimeout(500)
    assert(await page.locator('.record-stage video').evaluate(el=>el.currentTime>0&&!el.error))
    await page.screenshot({path:path.join(shots,'2026-10-01-video-detail.png')})
    await page.keyboard.press('Escape');await page.locator('.record-backdrop').waitFor({state:'hidden'})
    await page.locator('.side-nav').getByText('生活痕迹线').click()
    await page.locator('.line-tree button').filter({hasText:'云南旅程'}).click()
    await page.getByRole('button',{name:'编辑时间线',exact:true}).click()
    await page.locator('.line-form').getByLabel('名称',{exact:true}).fill('云南与上海')
    await page.getByRole('button',{name:'保存时间线',exact:true}).click()
    await page.locator('.line-tree button.active').filter({hasText:'云南与上海'}).waitFor()
    await page.getByRole('button',{name:'删除时间线',exact:true}).click()
    await page.locator('.confirm-card').getByRole('button',{name:'删除时间线',exact:true}).click()
    await page.locator('.line-tree button').filter({hasText:'云南与上海'}).waitFor({state:'hidden'})
    await page.locator('.side-nav').getByText('共同相册').click()
    await page.locator('.created-albums button').filter({hasText:'云南影集'}).click()
    await page.getByRole('button',{name:'编辑分册',exact:true}).click()
    await page.locator('.line-form').getByLabel('标题',{exact:true}).fill('我们的旅行影集')
    await page.getByRole('button',{name:'保存分册',exact:true}).click()
    await page.locator('#album-title-top').filter({hasText:'我们的旅行影集'}).waitFor()
    await page.getByRole('button',{name:'删除分册',exact:true}).click()
    await page.locator('.confirm-card').getByRole('button',{name:'删除分册',exact:true}).click()
    await page.locator('.created-albums button').filter({hasText:'我们的旅行影集'}).waitFor({state:'hidden'})
    assert((await json(await context.request.get(base+`/api/circles/${circle.id}/posts`))).length===3)
    await page.locator('.side-nav').getByText('圈子',{exact:true}).click()
    await page.getByRole('button',{name:'切换圈子',exact:true}).click()
    await page.getByPlaceholder('新圈名',{exact:true}).fill('第二个验证朋友圈')
    await page.getByRole('button',{name:'创建并切换',exact:true}).click()
    await page.getByRole('heading',{name:'第二个验证朋友圈',exact:true}).first().waitFor()
    await page.getByRole('button',{name:'圈子设置',exact:true}).click()
    await page.getByRole('button',{name:'解散圈子',exact:true}).click()
    await page.locator('.confirm-card').getByRole('button',{name:'解散',exact:true}).click()
    await page.getByRole('heading',{name:'独立旅行验证',exact:true}).first().waitFor()
    assert.deepEqual(failures,[])
    console.log('Workflow passed: timeline/album CRUD, multiple circles, ordered map route, sorted upload, record edit, comments, report/review, real video playback/seek.')
  }catch(e){if(page)await page.screenshot({path:path.join(shots,'workflow-failure.png')});if(adminPage)await adminPage.screenshot({path:path.join(shots,'workflow-admin-failure.png')});throw e}
  finally{
    const remaining=await json(await context.request.get(base+'/api/circles'))
    for(const c of remaining)await context.request.delete(base+`/api/circles/${c.id}`)
    await adminContext.request.post(adminBase+'/api/admin/auth/login',{data:{username:'admin',password:'admin123'}})
    const deletion=await adminContext.request.delete(adminBase+`/api/admin/users/${user.id}`,{data:{reason:'测试数据清理'}})
    assert(deletion.ok(),await deletion.text())
    await browser.close()
  }
}
main().catch(e=>{console.error(e);process.exit(1)})
